version: "3.8"

services:
  core-api:
    image: core-api:latest
    build:
      context: ./core-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  client-app:
    image: client-app:latest
    build:
      context: ./client-app
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - core-api
