version: "3.8"

services:
  core-api:
    image: core-api:latest
    build:
      context: ./core-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=secret
      - JWT_EXPIRES_IN=30m
      - TWILIGHT_URL=https://api3.twilightcyber.com

  client-app:
    image: client-app:latest
    build:
      context: ./client-app
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - core-api
    environment:
      - VITE_API_URL=http://core-api:3000
